/** @license React v16.9.0-alpha.0
 * react.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';(function(t,p){"object"===typeof exports&&"undefined"!==typeof module?module.exports=p():"function"===typeof define&&define.amd?define(p):t.React=p()})(this,function(){function t(a){for(var b="https://reactjs.org/docs/error-decoder.html?invariant="+a,c=1;c<arguments.length;c++)b+="&args[]="+encodeURIComponent(arguments[c]);return Error("Minified React error #"+a+"; visit "+b+" for the full message or use the non-minified dev environment for full errors and additional helpful warnings. ")}
function p(a,b,c){this.props=a;this.context=b;this.refs=Y;this.updater=c||Z}function aa(){}function K(a,b,c){this.props=a;this.context=b;this.refs=Y;this.updater=c||Z}function r(){if(!L&&null!==e){var a=e.expirationTime;M?N():M=!0;C(sa,a)}}function ba(){var a=e,b=e.next;if(e===b)e=null;else{var c=e.previous;e=c.next=b;b.previous=c}a.next=a.previous=null;c=a.callback;b=a.expirationTime;a=a.priorityLevel;var d=h,g=D;h=a;D=b;try{var n=c(x||1===a)}catch(ta){throw ta;}finally{h=d,D=g}if("function"===typeof n)if(n=
{callback:n,priorityLevel:a,expirationTime:b,next:null,previous:null},null===e)e=n.next=n.previous=n;else{c=null;a=e;do{if(a.expirationTime>=b){c=a;break}a=a.next}while(a!==e);null===c?c=e:c===e&&(e=n,r());b=c.previous;b.next=c.previous=n;n.next=c;n.previous=b}}function sa(a){M=!1;L=!0;var b=x;x=a;try{if(a)for(;null!==e;){var c=l();if(e.expirationTime<=c){do ba();while(null!==e&&e.expirationTime<=c)}else break}else if(null!==e){do ba();while(null!==e&&!E())}}finally{L=!1,x=b,r()}}function ca(a,b,
c){var d=void 0,g={},n=null,e=null;if(null!=b)for(d in void 0!==b.ref&&(e=b.ref),void 0!==b.key&&(n=""+b.key),b)da.call(b,d)&&!ea.hasOwnProperty(d)&&(g[d]=b[d]);var k=arguments.length-2;if(1===k)g.children=c;else if(1<k){for(var f=Array(k),h=0;h<k;h++)f[h]=arguments[h+2];g.children=f}if(a&&a.defaultProps)for(d in k=a.defaultProps,k)void 0===g[d]&&(g[d]=k[d]);return{$$typeof:y,type:a,key:n,ref:e,props:g,_owner:O.current}}function ua(a,b){return{$$typeof:y,type:a.type,key:b,ref:a.ref,props:a.props,
_owner:a._owner}}function P(a){return"object"===typeof a&&null!==a&&a.$$typeof===y}function va(a){var b={"=":"=0",":":"=2"};return"$"+(""+a).replace(/[=:]/g,function(a){return b[a]})}function fa(a,b,c,d){if(F.length){var g=F.pop();g.result=a;g.keyPrefix=b;g.func=c;g.context=d;g.count=0;return g}return{result:a,keyPrefix:b,func:c,context:d,count:0}}function ha(a){a.result=null;a.keyPrefix=null;a.func=null;a.context=null;a.count=0;10>F.length&&F.push(a)}function Q(a,b,c,d){var g=typeof a;if("undefined"===
g||"boolean"===g)a=null;var e=!1;if(null===a)e=!0;else switch(g){case "string":case "number":e=!0;break;case "object":switch(a.$$typeof){case y:case wa:e=!0}}if(e)return c(d,a,""===b?"."+R(a,0):b),1;e=0;b=""===b?".":b+":";if(Array.isArray(a))for(var f=0;f<a.length;f++){g=a[f];var k=b+R(g,f);e+=Q(g,k,c,d)}else if(null===a||"object"!==typeof a?k=null:(k=ia&&a[ia]||a["@@iterator"],k="function"===typeof k?k:null),"function"===typeof k)for(a=k.call(a),f=0;!(g=a.next()).done;)g=g.value,k=b+R(g,f++),e+=
Q(g,k,c,d);else if("object"===g)throw c=""+a,t(31,"[object Object]"===c?"object with keys {"+Object.keys(a).join(", ")+"}":c,"");return e}function S(a,b,c){return null==a?0:Q(a,"",b,c)}function R(a,b){return"object"===typeof a&&null!==a&&null!=a.key?va(a.key):b.toString(36)}function xa(a,b,c){a.func.call(a.context,b,a.count++)}function ya(a,b,c){var d=a.result,e=a.keyPrefix;a=a.func.call(a.context,b,a.count++);Array.isArray(a)?T(a,d,c,function(a){return a}):null!=a&&(P(a)&&(a=ua(a,e+(!a.key||b&&b.key===
a.key?"":(""+a.key).replace(ja,"$&/")+"/")+c)),d.push(a))}function T(a,b,c,d,e){var g="";null!=c&&(g=(""+c).replace(ja,"$&/")+"/");b=fa(b,g,d,e);S(a,ya,b);ha(b)}function q(){var a=ka.current;if(null===a)throw t(321);return a}function la(){}var f="function"===typeof Symbol&&Symbol.for,y=f?Symbol.for("react.element"):60103,wa=f?Symbol.for("react.portal"):60106,u=f?Symbol.for("react.fragment"):60107,U=f?Symbol.for("react.strict_mode"):60108,za=f?Symbol.for("react.profiler"):60114,Aa=f?Symbol.for("react.provider"):
60109,Ba=f?Symbol.for("react.context"):60110,Ca=f?Symbol.for("react.concurrent_mode"):60111,Da=f?Symbol.for("react.forward_ref"):60112,Ea=f?Symbol.for("react.suspense"):60113,Fa=f?Symbol.for("react.memo"):60115,Ga=f?Symbol.for("react.lazy"):60116,ia="function"===typeof Symbol&&Symbol.iterator,ma=Object.getOwnPropertySymbols,Ha=Object.prototype.hasOwnProperty,Ia=Object.prototype.propertyIsEnumerable,G=function(){try{if(!Object.assign)return!1;var a=new String("abc");a[5]="de";if("5"===Object.getOwnPropertyNames(a)[0])return!1;
var b={};for(a=0;10>a;a++)b["_"+String.fromCharCode(a)]=a;if("0123456789"!==Object.getOwnPropertyNames(b).map(function(a){return b[a]}).join(""))return!1;var c={};"abcdefghijklmnopqrst".split("").forEach(function(a){c[a]=a});return"abcdefghijklmnopqrst"!==Object.keys(Object.assign({},c)).join("")?!1:!0}catch(d){return!1}}()?Object.assign:function(a,b){if(null===a||void 0===a)throw new TypeError("Object.assign cannot be called with null or undefined");var c=Object(a);for(var d,e=1;e<arguments.length;e++){var f=
Object(arguments[e]);for(var h in f)Ha.call(f,h)&&(c[h]=f[h]);if(ma){d=ma(f);for(var k=0;k<d.length;k++)Ia.call(f,d[k])&&(c[d[k]]=f[d[k]])}}return c},Z={isMounted:function(a){return!1},enqueueForceUpdate:function(a,b,c){},enqueueReplaceState:function(a,b,c,d){},enqueueSetState:function(a,b,c,d){}},Y={};p.prototype.isReactComponent={};p.prototype.setState=function(a,b){if("object"!==typeof a&&"function"!==typeof a&&null!=a)throw t(85);this.updater.enqueueSetState(this,a,b,"setState")};p.prototype.forceUpdate=
function(a){this.updater.enqueueForceUpdate(this,a,"forceUpdate")};aa.prototype=p.prototype;f=K.prototype=new aa;f.constructor=K;G(f,p.prototype);f.isPureReactComponent=!0;var C=void 0,N=void 0,E=void 0,l=void 0,Ja=Date,Ka="function"===typeof setTimeout?setTimeout:void 0,La="function"===typeof clearTimeout?clearTimeout:void 0,na="function"===typeof requestAnimationFrame?requestAnimationFrame:void 0,oa="function"===typeof cancelAnimationFrame?cancelAnimationFrame:void 0,pa=void 0,qa=void 0,V=function(a){pa=
na(function(b){La(qa);a(b)});qa=Ka(function(){oa(pa);a(l())},100)};if("object"===typeof performance&&"function"===typeof performance.now){var Ma=performance;l=function(){return Ma.now()}}else l=function(){return Ja.now()};if("undefined"===typeof window||"function"!==typeof MessageChannel){var v=null,Na=function(a){if(null!==v)try{v(a)}finally{v=null}};C=function(a,b){null!==v?setTimeout(C,0,a):(v=a,setTimeout(Na,0,!1))};N=function(){v=null};E=function(){return!1}}else{"undefined"!==typeof console&&
("function"!==typeof na&&console.error("This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills"),"function"!==typeof oa&&console.error("This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills"));var w=null,H=!1,z=-1,A=!1,W=!1,I=0,J=33,B=33;E=function(){return I<=l()};f=new MessageChannel;var ra=f.port2;f.port1.onmessage=function(a){H=!1;a=
w;var b=z;w=null;z=-1;var c=l(),d=!1;if(0>=I-c)if(-1!==b&&b<=c)d=!0;else{A||(A=!0,V(X));w=a;z=b;return}if(null!==a){W=!0;try{a(d)}finally{W=!1}}};var X=function(a){if(null!==w){V(X);var b=a-I+B;b<B&&J<B?(8>b&&(b=8),B=b<J?J:b):J=b;I=a+B;H||(H=!0,ra.postMessage(void 0))}else A=!1};C=function(a,b){w=a;z=b;W||0>b?ra.postMessage(void 0):A||(A=!0,V(X))};N=function(){w=null;H=!1;z=-1}}var e=null,x=!1,h=3,m=-1,D=-1,L=!1,M=!1,Oa=0,ka={current:null},O={current:null};f={ReactCurrentDispatcher:ka,ReactCurrentOwner:O,
ReactShouldWarnActingUpdates:{current:!1},assign:G};G(f,{Scheduler:{unstable_ImmediatePriority:1,unstable_UserBlockingPriority:2,unstable_NormalPriority:3,unstable_IdlePriority:5,unstable_LowPriority:4,unstable_runWithPriority:function(a,b){switch(a){case 1:case 2:case 3:case 4:case 5:break;default:a=3}var c=h,d=m;h=a;m=l();try{return b()}catch(g){throw r(),g;}finally{h=c,m=d}},unstable_next:function(a){switch(h){case 1:case 2:case 3:var b=3;break;default:b=h}var c=h,d=m;h=b;m=l();try{return a()}catch(g){throw r(),
g;}finally{h=c,m=d}},unstable_scheduleCallback:function(a,b,c){var d=-1!==m?m:l();if("object"===typeof c&&null!==c&&"number"===typeof c.timeout)c=d+c.timeout;else switch(a){case 1:c=d+-1;break;case 2:c=d+250;break;case 5:c=d+1073741823;break;case 4:c=d+1E4;break;default:c=d+5E3}a={callback:b,priorityLevel:a,expirationTime:c,next:null,previous:null};if(null===e)e=a.next=a.previous=a,r();else{b=null;d=e;do{if(d.expirationTime>c){b=d;break}d=d.next}while(d!==e);null===b?b=e:b===e&&(e=a,r());c=b.previous;
c.next=b.previous=a;a.next=b;a.previous=c}return a},unstable_cancelCallback:function(a){var b=a.next;if(null!==b){if(b===a)e=null;else{a===e&&(e=b);var c=a.previous;c.next=b;b.previous=c}a.next=a.previous=null}},unstable_wrapCallback:function(a){var b=h;return function(){var c=h,d=m;h=b;m=l();try{return a.apply(this,arguments)}catch(g){throw r(),g;}finally{h=c,m=d}}},unstable_getCurrentPriorityLevel:function(){return h},unstable_shouldYield:function(){return!x&&(null!==e&&e.expirationTime<D||E())},
unstable_continueExecution:function(){null!==e&&r()},unstable_pauseExecution:function(){},unstable_getFirstCallbackNode:function(){return e},get unstable_now(){return l}},SchedulerTracing:{get __interactionsRef(){return null},get __subscriberRef(){return null},unstable_clear:function(a){return a()},unstable_getCurrent:function(){return null},unstable_getThreadID:function(){return++Oa},unstable_trace:function(a,b,c){return c()},unstable_wrap:function(a){return a},unstable_subscribe:function(a){},unstable_unsubscribe:function(a){}}});
var da=Object.prototype.hasOwnProperty,ea={key:!0,ref:!0,__self:!0,__source:!0},ja=/\/+/g,F=[];u={Children:{map:function(a,b,c){if(null==a)return a;var d=[];T(a,d,null,b,c);return d},forEach:function(a,b,c){if(null==a)return a;b=fa(null,null,b,c);S(a,xa,b);ha(b)},count:function(a){return S(a,function(){return null},null)},toArray:function(a){var b=[];T(a,b,null,function(a){return a});return b},only:function(a){if(!P(a))throw t(143);return a}},createRef:function(){return{current:null}},Component:p,
PureComponent:K,createContext:function(a,b){void 0===b&&(b=null);a={$$typeof:Ba,_calculateChangedBits:b,_currentValue:a,_currentValue2:a,_threadCount:0,Provider:null,Consumer:null};a.Provider={$$typeof:Aa,_context:a};return a.Consumer=a},forwardRef:function(a){return{$$typeof:Da,render:a}},lazy:function(a){return{$$typeof:Ga,_ctor:a,_status:-1,_result:null}},memo:function(a,b){return{$$typeof:Fa,type:a,compare:void 0===b?null:b}},error:la,warn:la,useCallback:function(a,b){return q().useCallback(a,
b)},useContext:function(a,b){return q().useContext(a,b)},useEffect:function(a,b){return q().useEffect(a,b)},useImperativeHandle:function(a,b,c){return q().useImperativeHandle(a,b,c)},useDebugValue:function(a,b){},useLayoutEffect:function(a,b){return q().useLayoutEffect(a,b)},useMemo:function(a,b){return q().useMemo(a,b)},useReducer:function(a,b,c){return q().useReducer(a,b,c)},useRef:function(a){return q().useRef(a)},useState:function(a){return q().useState(a)},Fragment:u,Profiler:za,StrictMode:U,
Suspense:Ea,createElement:ca,cloneElement:function(a,b,c){if(null===a||void 0===a)throw t(267,a);var d=void 0,e=G({},a.props),f=a.key,h=a.ref,k=a._owner;if(null!=b){void 0!==b.ref&&(h=b.ref,k=O.current);void 0!==b.key&&(f=""+b.key);var l=void 0;a.type&&a.type.defaultProps&&(l=a.type.defaultProps);for(d in b)da.call(b,d)&&!ea.hasOwnProperty(d)&&(e[d]=void 0===b[d]&&void 0!==l?l[d]:b[d])}d=arguments.length-2;if(1===d)e.children=c;else if(1<d){l=Array(d);for(var m=0;m<d;m++)l[m]=arguments[m+2];e.children=
l}return{$$typeof:y,type:a.type,key:f,ref:h,props:e,_owner:k}},createFactory:function(a){var b=ca.bind(null,a);b.type=a;return b},isValidElement:P,version:"16.9.0-alpha.0",unstable_ConcurrentMode:Ca,__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED:f};u=(U={default:u},u)||U;return u.default||u});